global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nexp
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: dexp
    scrape_interval: 5s
    static_configs:
    - targets: ['docker-exporter:8080']
